server:
  port: 8501


spring:
  application:
    name: account-service
  zipkin: 
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}
      
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

management:
  endpoints:
    web:
      exposure:
        include: "*"
    
spcloud:
  cassandra:
    keyspace:
      name: ${CASSANDRA_SERVER_KEYSPACE:springcloud}
      
    port: ${CASSANDRA_SERVER_PORT:9042}
    
    contact:
      point: ${CASSANDRA_SERVER_HOST:localhost}
      
    getEntityBasePackages: com.mehmetpekdemir.commonservice
    
    username: ${CASSANDRA_SERVER_USERNAME:cassandra}
    password: ${CASSANDRA_SERVER_USERNAME:cassandra}


eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
      
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}
       
    