server:
  port: 8501


spring:
  application:
    name: account-service
    
    
spcloud:
  cassandra:
    keyspace:
      name: springcloud
    port: 9042
    contact:
      point: 127.0.0.1
    getEntityBasePackages: com.mehmetpekdemir.commonservice
    username: cassandra
    password: cassandra


eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
       
    